### ISSUE TITLE
footer bug

### ISSUE THREAD

**Issue by maxirozay** [larucheio/laruche.io#38]
![image](https://cloud.githubusercontent.com/assets/12101710/22481242/c917265c-e7f4-11e6-9934-f966a83ca3ed.png)
![image](https://cloud.githubusercontent.com/assets/12101710/22481257/dc3dc2ae-e7f4-11e6-814e-1f4e07da56da.png)
![image](https://cloud.githubusercontent.com/assets/12101710/22481267/e657ef9e-e7f4-11e6-80dc-c4d742f46bef.png)

**Comment by maxirozay** [comment]
Is the border suppose to stick to the bottom if the page content is short?

**Comment by rspt** [comment]
The problem in the first pic (contact page) is fixed in PR #33 .

Otherwise no it's not supposed to flow to the bottom but simply following the page content.
