### ISSUE TITLE
Redesign the mobile menu

### ISSUE THREAD

**Issue by rspt** [larucheio/laruche.io#44]

**Comment by maxirozay** [comment]
![image](https://cloud.githubusercontent.com/assets/12101710/22561784/0f485606-e97a-11e6-90a4-9e3988cbbcd7.png)
![image](https://cloud.githubusercontent.com/assets/12101710/22561792/1c4c96aa-e97a-11e6-9b8e-afdd9376ad2e.png)

**Comment by maxirozay** [comment]
![image](https://cloud.githubusercontent.com/assets/12101710/22561928/c771139e-e97a-11e6-8273-5603658eea39.png)

bigger font

**Comment by maxirozay** [comment]
![image](https://cloud.githubusercontent.com/assets/12101710/22562783/4935192c-e97e-11e6-9512-ae834c809088.png)

**Comment by rspt** [comment]
I like the last one! Will make some propositions to discuss too :)
