### ISSUE TITLE
Design questions

### ISSUE THREAD

**Issue by maxirozay** [larucheio/laruche.io#46]

**Comment by maxirozay** [comment]
![image](https://cloud.githubusercontent.com/assets/12101710/22562416/b8b7d9b2-e97c-11e6-853b-962d0b064cc4.png)
Is it normal to have a border on the last element? I'd like it better without it.

**Comment by rspt** [comment]
> Is it normal to have a border on the last element? I'd like it better without it.

No it is not, I've already noticed it and was thinking about removing it too :)

**Comment by rspt** [comment]
Fixed by #47
